// <auto-generated />
namespace LiteDispatch.DbContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrackingEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackingEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "201306052320059_TrackingEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
