// <auto-generated />
namespace LiteDispatch.DbContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Pascal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pascal));
        
        string IMigrationMetadata.Id
        {
            get { return "201305230023421_Pascal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
